<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<Version>1.0.0</Version>
 </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.GLFW" Version="2.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XcyUI\XcyUI.csproj" />
  </ItemGroup>

</Project>
